INSERT INTO categories (id, parent_id, category, color) VALUES (1, 'parent', 'Mobilier', 'mobilier');
INSERT INTO categories (id, parent_id, category, color) VALUES (2, 'parent', 'Appareils électriques', 'appareils-electrique');
INSERT INTO categories (id, parent_id, category, color) VALUES (3, 'parent', 'Vêtements adultes et accessoires', 'vetements-adulte');
INSERT INTO categories (id, parent_id, category, color) VALUES (4, 'parent', 'Livres', 'livres-adultes');
INSERT INTO categories (id, parent_id, category, color) VALUES (5, 'parent', 'Enfants / bébés', 'enfants');
INSERT INTO categories (id, parent_id, category, color) VALUES (6, 'parent', 'Vaisselle Décoration', 'vaisselle');
INSERT INTO categories (id, parent_id, category, color) VALUES (7, 'parent', 'Bricolage Jardinage loisirs bureau sport', 'bricolage');
INSERT INTO categories (id, parent_id, category, color) VALUES (8, 'parent', 'Hors boutique', 'autres');
INSERT INTO categories (id, parent_id, category, color) VALUES (9, 'Mobilier', 'Bibliothèque', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (10, 'Mobilier', 'Armoire', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (11, 'Mobilier', 'Commode', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (12, 'Mobilier', 'Table de chevet', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (13, 'Mobilier', 'Meuble TV', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (14, 'Mobilier', 'Lit', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (15, 'Appareils électriques', 'TV', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (16, 'Appareils électriques', 'Petit électroménager (Grille-pain, bouilloire...)', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (17, 'Appareils électriques', 'Hifi', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (18, 'Appareils électriques', 'Divertissement (Console...)', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (19, 'Vêtements adultes et linge de maison / accessoires', 'Vêtements', 'vetements-adulte');
INSERT INTO categories (id, parent_id, category, color) VALUES (20, 'Vêtements adultes et linge de maison / accessoires', 'Linge de maison', 'linge-de-maison');
INSERT INTO categories (id, parent_id, category, color) VALUES (21, 'Livres', 'Livres', 'livres-adultes');
INSERT INTO categories (id, parent_id, category, color) VALUES (22, 'Livres', 'CD/DVD', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (23, 'Enfants / bébés', 'Vêtements', 'vetements-enfants');
INSERT INTO categories (id, parent_id, category, color) VALUES (24, 'Enfants / bébés', 'bébé', 'puericulture');
INSERT INTO categories (id, parent_id, category, color) VALUES (26, 'Enfants / bébés', 'Jeux-Jouets', 'jouets');
INSERT INTO categories (id, parent_id, category, color) VALUES (27, 'Enfants / bébés', 'Peluches', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (28, 'Vaisselle Décoration', 'Vaisselle', 'vaisselle');
INSERT INTO categories (id, parent_id, category, color) VALUES (29, 'Vaisselle Décoration', 'Ustensile de cuisine', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (30, 'Vaisselle Décoration', 'Décoration diverse', 'decoration');
INSERT INTO categories (id, parent_id, category, color) VALUES (31, 'Bricolage jardinage loisirs bureau sport', 'Outils de bricolage', 'Outils-de-bricolage');
INSERT INTO categories (id, parent_id, category, color) VALUES (32, 'Bricolage jardinage loisirs bureau sport', 'Outils de jardinage', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (33, 'Bricolage jardinage loisirs bureau sport', 'Hobbies/bureau/bricolage', 'divers-hobby');
INSERT INTO categories (id, parent_id, category, color) VALUES (34, 'Bricolage jardinage loisirs bureau sport', 'Outils pour le vélo', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (35, 'Bricolage jardinage loisirs bureau sport', 'Instruments de musique', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (36, 'Livres', 'Vinyles', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (39, 'autre', 'Vente pour activités annexes', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (40, 'Mobilier', 'Autres', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (41, 'Vaisselle Décoration', 'Luminaire', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (42, 'Mobilier', 'Sièges/fauteuils', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (44, 'Vêtements adultes et linge de maison / accessoires', 'Sacs, valises...', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (45, 'Vêtements adultes et linge de maison / accessoires', 'Chaussures', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (46, 'Appareils électriques', 'Ordi et matériel allant avec', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (48, 'Mobilier', 'Petite table', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (49, 'Enfants / bébés', 'Chaise enfant propreté ', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (53, 'Mobilier', 'Essai', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (54, 'Livres', 'Romans ', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (55, 'autre', 'Sacs', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (56, 'autre', 'Parfums, accessoires toilette ...', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (57, 'autre', 'articles scolaires', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (58, 'Bricolage jardinage loisirs bureau sport', 'Jeux', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (59, 'Bricolage jardinage loisirs bureau sport', 'Accessoires voiture ', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (60, 'autre', 'Animaux ', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (61, 'autre', 'Outils', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (62, 'autre', 'Outils', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (63, 'autre', 'Outils', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (64, 'autre', 'Vinyles', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (67, 'Bricolage jardinage loisirs bureau sport', 'Sport voyage', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (68, 'Vêtements adultes et linge de maison / accessoires', 'ceinture, foulards', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (69, 'autre', 'Accessoires', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (70, 'Vêtements adultes et linge de maison / accessoires', 'Manteau', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (71, 'Appareils électriques', 'Radiateur ', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (72, 'Mobilier', 'Canapé ', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (73, 'Mobilier', 'Table', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (74, 'autre', 'laine', '');
INSERT INTO categories (id, parent_id, category, color) VALUES (76, 'autre', 'Sport', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (77, 'autre', 'Bureautique ', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (78, 'Vaisselle Décoration', 'Vaisselle', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (79, 'Appareils électriques', 'Téléphones et accessoires ', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (81, 'Mobilier', 'Enfant', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (82, 'Mobilier', 'Enfant', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (83, 'autre', 'Objets diverses', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (84, 'Enfants / bébés', 'Deguisement', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (86, 'Vêtements adultes et linge de maison / accessoires', 'Accessoires', 'vetements-adulte');
INSERT INTO categories (id, parent_id, category, color) VALUES (87, 'autre', 'Ménage ', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (88, 'Mobilier', 'Materiel de menage - linge', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (89, 'Appareils électriques', 'Glacière électrique ', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (90, 'Enfants / bébés', 'Puzzles', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (91, 'Livres', 'Livres', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (92, 'Bricolage jardinage loisirs bureau sport', 'Dvd', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (94, 'Hors boutique', 'Adhésion', 'autres');
INSERT INTO categories (id, parent_id, category, color) VALUES (95, 'Appareils électriques', 'Autre', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (96, 'Enfants / bébés', 'Jouet', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (98, 'Vaisselle Décoration', 'miroir', 'None');
INSERT INTO categories (id, parent_id, category, color) VALUES (99, 'Hors boutique', 'Oeuvres', 'autres');
INSERT INTO categories (id, parent_id, category, color) VALUES (100, 'parent', 'Linge de maison et mercerie', 'None');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (2, 'Jeux-Jouets', 'Lot de 4 (figurines, petites voitures, petits poneys)', '5', 26, '50');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (5, 'Peluches', 'Peluche (petit modèle)', '5', 26, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (6, 'Jeux-Jouets', 'Légos / Playmobiles (lot)', '5', 26, '200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (7, 'Jeux-Jouets', 'Puzzle', '5', 26, '200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (9, 'Jeux-Jouets', 'Poupée', '5', 26, '200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (12, 'Jeux-Jouets', 'Gros jouets', '5', 26, '700');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (15, 'bébé', 'Baignoire', '5', 24, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (17, 'bébé', 'Table à langer', '5', 24, '500');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (18, 'bébé', 'Tapis d''éveil / transat', '5', 24, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (20, 'bébé', 'Chaise haute', '5', 24, '600');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (21, 'bébé', 'Lit (barreaux ou parapluie)', '5', 24, '1000');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (22, 'bébé', 'Siège auto', '5', 24, '900');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (26, 'Vêtements', 'Chapeau / body / collants / legging', '5', 23, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (28, 'Vêtements', 'Chaussons', '5', 23, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (31, 'Vêtements', 'Short / T-shirt / pyjama / maillot de bain', '5', 23, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (34, 'Vêtements', 'Déguisement', '5', 23, '150');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (35, 'Vêtements', 'Jupe / robe / pull / pantalon', '5', 23, '200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (39, 'Vêtements', 'Chaussures', '5', 23, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (40, 'Vêtements', 'Blouson', '5', 23, '400');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (41, 'Vêtements', 'Manteau', '5', 23, '500');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (56, 'Livres', 'Livre de poche', '4', 21, '50');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (58, 'Livres', 'BD-Livre broché', '4', 21, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (59, 'Disques', 'CD / DVD', '4', 21, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (61, 'Disques', 'Petit vinyle', '4', 21, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (62, 'Disques', 'Jeu vidéo', '4', 21, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (65, 'Assise', 'Chaise', '1', 1, '400');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (66, 'Assise', 'Fauteuil, rocking chair', '1', 1, '1000');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (68, 'Table', 'Table basse / petit mobilier', '1', 1, '800');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (69, 'Table', 'Bureau / table', '1', 1, '1500');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (71, 'Armoire', 'Armoire, buffet', '1', 1, '4000');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (77, 'Vaisselle', 'Bols / tasses / verres / assiettes (lot)', '6', 28, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (82, 'Vaisselle', 'Poêle, casserole', '6', 28, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (84, 'Accessoires', 'Bijoux fantaisie', '3', 86, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (87, 'Vêtements', 'Short / T-shirt / nuisette', '3', 19, '200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (89, 'Vêtements', 'Chemise / jupe /pantalon / pull', '3', 19, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (94, 'Vêtements', 'Robe', '3', 19, '400');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (95, 'Vêtements', 'Gilet / veste', '3', 19, '400');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (96, 'Vêtements', 'Ensemble ski', '3', 19, '1000');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (97, 'Vêtements', 'Chaussures', '3', 19, '500');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (100, 'Vêtements', 'Manteau / veste chaude / anorak', '3', 19, '800');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (103, 'Linge de maison', 'Serviette de table', '100', 100, '50');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (104, 'Linge de maison', 'Taie d''oreiller', '100', 100, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (107, 'Linge de maison', 'Nappe', '100', 100, '150');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (108, 'Linge de maison', 'Rideaux', '100', 100, '200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (109, 'Linge de maison', 'Drap', '100', 100, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (110, 'Linge de maison', 'Housse de couette', '100', 100, '400');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (111, 'Linge de maison', 'Dessus de lit', '100', 100, '400');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (112, 'Linge de maison', 'Couette (petit modèle)', '100', 100, '400');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (113, 'Linge de maison', 'Couette (grand modèle)', '100', 100, '600');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (118, 'Décoration', 'Petite décoration (boites, bibelots, bougeoirs…)', '6', 30, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (119, 'Décoration', 'Pots / Vases', '6', 30, '200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (122, 'Décoration', 'Lampes sur pied ou à poser', '6', 30, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (124, 'Décoration', 'Grande décoration (globe…)', '6', 30, '400');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (127, 'Petit électro-ménager', 'Petits appareils électriques et electroménagers', '2', 2, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (139, 'Petit électro-ménager', 'Gros appareils électriques et electroménagers', '2', 2, '1200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (144, 'Divertissement', 'Tablette / téléphone', '2', 2, '1800');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (145, 'sport-voyage', 'Vélo d''appartement', '7', 67, '2000');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (146, 'TV', 'Télévision écran plat, petit format', '2', 2, '2500');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (152, 'Linge de maison', 'Serviette de bain', '100', 100, '200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (154, 'Linge de maison', 'Coussin / Coussin chaise', '100', 100, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (155, 'Vêtements', 'Ceinture', '3', 19, '200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (157, 'bébé', 'Poussette', '5', 24, '700');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (160, 'Jeux-Jouets', 'Petits jouets', '5', 26, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (163, 'Peluches', 'Peluche (grand modèle)', '5', 26, '200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (164, 'Décoration', 'Tapis', '6', 30, '400');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (190, 'bébé', 'Autre', '5', 24, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (193, 'Vêtements', 'Autre', '5', 23, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (194, 'Jeux-Jouets', 'Autre', '5', 26, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (195, 'Vêtements', 'Autre', '3', 19, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (196, 'Linge de maison', 'Autre', '100', 100, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (197, 'Décoration', 'Autre', '6', 30, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (198, 'Vaisselle', 'Autre', '6', 28, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (205, 'Accessoires', 'Montre', '3', 86, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (206, 'Vêtements', 'Chaussons', '3', 19, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (207, 'Jeux-Jouets', 'Jeu de société', '5', 26, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (208, 'Accessoires', 'Autre', '3', 86, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (209, 'Livres', 'Autre', '4', 21, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (210, 'Mobilier', 'Autre', '1', 1, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (211, 'Divertissement', 'Autre', '2', 2, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (212, 'Divertissement', 'Autre', '7', 33, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (213, 'Adhésion Asso', 'Adhésion 2025', '8', 94, '1500');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (214, 'bébé', 'Hochet / livre', '5', 24, '50');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (215, 'bébé', 'body / collant', '5', 24, '50');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (216, 'bébé', 'Chemise / chaussure / pantalon / pyjama', '5', 24, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (217, 'bébé', 'Manteau', '5', 24, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (218, 'bébé', 'Gigoteuse', '5', 24, '200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (219, 'bébé', 'Petit vélo / draisienne', '5', 24, '400');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (220, 'Vêtements', 'Ensemble ski (haut+bas)', '5', 23, '700');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (221, 'sport voyage', 'Matériel de sport', '7', 67, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (222, 'sport voyage', 'Casque', '7', 67, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (223, 'sport voyage', 'Valise / Sac à dos', '7', 67, '700');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (224, 'sport voyage', 'Trotinette', '7', 67, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (225, 'sport voyage', 'Vélo (3-12 ans)', '7', 67, '500');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (226, 'sport voyage', 'Vélo (ado-adulte)', '7', 67, '1200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (227, 'hobbies/bureau', 'Loisirs créatifs', '7', 33, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (228, 'hobbies/bureau', 'Fournitures de bureau (lot)', '7', 33, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (229, 'Linge de maison et mercerie', 'Mercerie', '100', 100, '10');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (230, 'Linge de maison et mercerie', 'Mercerie', '100', 100, '20');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (231, 'Linge de maison et mercerie', 'Mercerie', '100', 100, '50');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (232, 'hobbies/bureau', 'Jardinage', '7', 33, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (233, 'hobbies/bureau', 'Bricolage', '7', 33, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (234, 'Disques', 'Grand vinyle', '4', 21, '200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (235, 'Sièges/fauteuils', 'Canapé', '1', 1, '4000');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (236, 'Vaisselle', 'Saladier / plat', '6', 28, '200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (237, 'Vaisselle', 'Grands ustensiles (marmites...)', '6', 28, '500');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (238, 'Vaisselle', 'Petits ustensiles (couverts, économes...)', '6', 28, '50');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (239, 'Décoration', 'Cadre ou tableau', '6', 30, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (240, 'Vaisselle', 'Assiettes dépareillées', '6', 28, '10');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (241, 'Vaisselle', 'Point jaune', '6', 28, '50');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (242, 'Décoration', 'Point jaune', '6', 30, '50');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (243, 'Accessoires', 'Petit sac', '3', 86, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (244, 'Accessoires', 'Grand sac', '3', 86, '500');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (245, 'Accessoires', 'Cravates / ceintures / chapeaux / foulards ', '3', 86, '200');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (246, 'Accessoires', 'Etuis / porte-monnaie', '3', 86, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (247, 'Vêtements', 'Blouson', '3', 19, '600');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (248, 'Vêtements', 'Chaussures (toiles-nus pieds)', '3', 19, '300');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (251, 'Hifi', 'Matériel Hifi', '2', 2, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (252, 'Hifi', 'Matériel informatique', '2', 2, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (253, 'Vêtements', 'Braderie (1euro)', '3', 19, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (254, 'Livres', 'Braderie (1euro)', '4', 21, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (255, 'Vaisselle', 'Braderie (1euro)', '6', 28, '100');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (256, 'Oeuvre', 'Téléthon', '8', 99, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (257, 'Oeuvre', 'Octobre rose', '8', 99, '0');
INSERT INTO boutons_ventes (id_bouton, sous_categorie, nom, id_cat, id_souscat, prix) VALUES (258, 'Oeuvre', 'Asso Noël', '8', 99, '0');